In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('attendance.csv')

### Question 1: Sort the index.

In [16]:
df.sort_index()

            Date                  Away                   Home  Attendance Type
0     2021-04-01        Houston Astros      Oakland Athletics       10436    R
1     2021-04-01  Arizona Diamondbacks       San Diego Padres       10350    R
2     2021-04-01  San Francisco Giants       Seattle Mariners        8174    R
3     2021-04-01        Atlanta Braves  Philadelphia Phillies        8529    R
4     2021-04-01        Tampa Bay Rays          Miami Marlins        7062    R
...          ...                   ...                    ...         ...  ...
2365  2021-10-03      Colorado Rockies   Arizona Diamondbacks       12565    R
2366  2021-10-03     Oakland Athletics         Houston Astros       29752    R
2367  2021-10-03       Minnesota Twins     Kansas City Royals       17158    R
2368  2021-10-03     Milwaukee Brewers    Los Angeles Dodgers       43170    R
2369  2021-10-03        Boston Red Sox   Washington Nationals       33986    R

[2370 rows x 5 columns]

### Question 2: Set the index to a string column, sort the index, and slice by a substring of index values.

In [20]:
df = pd.read_csv('attendance.csv', index_col=['Date']).sort_index()
df.loc['2021-04-01':'2021-04-05']

                            Away                   Home  Attendance Type
Date
2021-04-01        Houston Astros      Oakland Athletics       10436    R
2021-04-01  Arizona Diamondbacks       San Diego Padres       10350    R
2021-04-01  San Francisco Giants       Seattle Mariners        8174    R
2021-04-01        Atlanta Braves  Philadelphia Phillies        8529    R
2021-04-01        Tampa Bay Rays          Miami Marlins        7062    R
2021-04-01     Toronto Blue Jays       New York Yankees       10850    R
2021-04-01       Minnesota Twins      Milwaukee Brewers       11740    R
2021-04-01     Chicago White Sox     Los Angeles Angels       13207    R
2021-04-01    Pittsburgh Pirates           Chicago Cubs       10343    R
2021-04-01   St. Louis Cardinals        Cincinnati Reds       12264    R
2021-04-01   Los Angeles Dodgers       Colorado Rockies       20570    R
2021-04-01     Cleveland Indians         Detroit Tigers        8000    R
2021-04-01         Texas Rangers     Kansas City Royals        9155    R
2021-04-02        Houston Astros      Oakland Athletics        5446    R
2021-04-02  Arizona Diamondbacks       San Diego Padres       10350    R
2021-04-02  San Francisco Giants       Seattle Mariners        8392    R
2021-04-02        Tampa Bay Rays          Miami Marlins        6115    R
2021-04-02     Chicago White Sox     Los Angeles Angels       12763    R
2021-04-02     Baltimore Orioles         Boston Red Sox        4452    R
2021-04-02   Los Angeles Dodgers       Colorado Rockies       20363    R
2021-04-03        Houston Astros      Oakland Athletics        5803    R
2021-04-03  Arizona Diamondbacks       San Diego Padres       10350    R
2021-04-03  San Francisco Giants       Seattle Mariners        8651    R
2021-04-03        Atlanta Braves  Philadelphia Phillies        8582    R
2021-04-03        Tampa Bay Rays          Miami Marlins        6179    R
2021-04-03     Toronto Blue Jays       New York Yankees       10107    R
2021-04-03       Minnesota Twins      Milwaukee Brewers       11383    R
2021-04-03     Chicago White Sox     Los Angeles Angels       12043    R
2021-04-03     Baltimore Orioles         Boston Red Sox        4571    R
2021-04-03    Pittsburgh Pirates           Chicago Cubs       10343    R
2021-04-03   St. Louis Cardinals        Cincinnati Reds       12213    R
2021-04-03   Los Angeles Dodgers       Colorado Rockies       20688    R
2021-04-03     Cleveland Indians         Detroit Tigers        8000    R
2021-04-03         Texas Rangers     Kansas City Royals        8889    R
2021-04-04        Houston Astros      Oakland Athletics        4504    R
2021-04-04  Arizona Diamondbacks       San Diego Padres       10350    R
2021-04-04        Atlanta Braves  Philadelphia Phillies       10773    R
2021-04-04     Toronto Blue Jays       New York Yankees       10066    R
2021-04-04       Minnesota Twins      Milwaukee Brewers       10666    R
2021-04-04     Chicago White Sox     Los Angeles Angels       12396    R
2021-04-04     Baltimore Orioles         Boston Red Sox        4458    R
2021-04-04    Pittsburgh Pirates           Chicago Cubs       10343    R
2021-04-04   St. Louis Cardinals        Cincinnati Reds       11629    R
2021-04-04   Los Angeles Dodgers       Colorado Rockies       20368    R
2021-04-04     Cleveland Indians         Detroit Tigers        8000    R
2021-04-04         Texas Rangers     Kansas City Royals        8869    R
2021-04-05   Los Angeles Dodgers      Oakland Athletics        6653    R
2021-04-05  San Francisco Giants       San Diego Padres       10350    R
2021-04-05     Chicago White Sox       Seattle Mariners        6436    R
2021-04-05     Toronto Blue Jays          Texas Rangers       38238    R
2021-04-05         New York Mets  Philadelphia Phillies       10782    R
2021-04-05   St. Louis Cardinals          Miami Marlins        4605    R
2021-04-05     Baltimore Orioles       New York Yankees        9008    R
2021-04-05        Houston Astros     Los Angeles Angels       13447    R
2021-04-05        Tampa Bay Rays         Boston Red Sox        4577    R
2021-04-05     Milwaukee Brewers           Chicago Cubs       10343    R
2021-04-05    Pittsburgh Pirates        Cincinnati Reds        9097    R
2021-04-05    Kansas City Royals      Cleveland Indians        8914    R
2021-04-05       Minnesota Twins         Detroit Tigers        7232    R

### Question 3: Sort by a single column.

In [23]:
df.sort_values(by=['Home'])

                            Away                  Home  Attendance Type
Date
2021-07-02  San Francisco Giants  Arizona Diamondbacks       12262    R
2021-09-26   Los Angeles Dodgers  Arizona Diamondbacks       16648    R
2021-09-08         Texas Rangers  Arizona Diamondbacks        6354    R
2021-08-14      San Diego Padres  Arizona Diamondbacks       16716    R
2021-04-13     Oakland Athletics  Arizona Diamondbacks        7010    R
...                          ...                   ...         ...  ...
2021-06-28         New York Mets  Washington Nationals       19150    R
2021-09-03         New York Mets  Washington Nationals       26779    R
2021-04-21   St. Louis Cardinals  Washington Nationals        7769    R
2021-04-06        Atlanta Braves  Washington Nationals        4801    R
2021-10-03        Boston Red Sox  Washington Nationals       33986    R

[2370 rows x 4 columns]

### Question 4: Sort by a single column in descending order.

In [24]:
df.sort_values(by=['Home'], ascending=False)

                             Away                  Home  Attendance Type
Date
2021-10-03         Boston Red Sox  Washington Nationals       33986    R
2021-07-31           Chicago Cubs  Washington Nationals       31444    R
2021-05-11  Philadelphia Phillies  Washington Nationals        8559    R
2021-04-20    St. Louis Cardinals  Washington Nationals        8418    R
2021-08-31  Philadelphia Phillies  Washington Nationals       16844    R
...                           ...                   ...         ...  ...
2021-04-10        Cincinnati Reds  Arizona Diamondbacks       13208    R
2021-04-29       Colorado Rockies  Arizona Diamondbacks        6843    R
2021-05-13          Miami Marlins  Arizona Diamondbacks        5967    R
2021-08-04   San Francisco Giants  Arizona Diamondbacks        8091    R
2021-09-01       San Diego Padres  Arizona Diamondbacks        5945    R

[2370 rows x 4 columns]

### Question 5: Sort by two columns.

In [25]:
df.sort_values(by=['Home', 'Away'])

                           Away                  Home  Attendance Type
Date
2021-09-20       Atlanta Braves  Arizona Diamondbacks        9642    R
2021-09-21       Atlanta Braves  Arizona Diamondbacks        8879    R
2021-09-22       Atlanta Braves  Arizona Diamondbacks       10631    R
2021-09-23       Atlanta Braves  Arizona Diamondbacks        6880    R
2021-07-16         Chicago Cubs  Arizona Diamondbacks       22046    R
...                         ...                   ...         ...  ...
2021-04-21  St. Louis Cardinals  Washington Nationals        7769    R
2021-06-29       Tampa Bay Rays  Washington Nationals       17117    R
2021-06-30       Tampa Bay Rays  Washington Nationals       15552    R
2021-08-17    Toronto Blue Jays  Washington Nationals       20060    R
2021-08-18    Toronto Blue Jays  Washington Nationals       18336    R

[2370 rows x 4 columns]

### Question 6: Sort by the last letter of a string column.

In [32]:
df.set_index(df['Home'].str[-1]).sort_index()

                       Away                  Home  Attendance Type
Home
s            Houston Astros     Oakland Athletics       10436    R
s     Philadelphia Phillies  Washington Nationals       17417    R
s            Houston Astros   Los Angeles Dodgers       52692    R
s            Boston Red Sox        Detroit Tigers       15724    R
s              Chicago Cubs      Colorado Rockies       38188    R
...                     ...                   ...         ...  ...
x         Toronto Blue Jays        Boston Red Sox       25257    R
x             Texas Rangers        Boston Red Sox       27652    R
x           Minnesota Twins     Chicago White Sox        8393    R
x         Oakland Athletics        Boston Red Sox        9272    R
x        Kansas City Royals     Chicago White Sox        9928    R

[2370 rows x 4 columns]