In [46]:
import pandas as pd
from random import normalvariate

In [17]:
df = pd.read_csv('attendance.csv', index_col=['Date']).sort_index()

### Question 1: Melt two numeric columns values into a single column. Add a new column to indicate what the values mean.

In [74]:
df['A Random Number'] = 42
df_melt = df.melt(id_vars=['Home', 'Away'], var_name='Type', value_name='Number', value_vars=['Attendance', 'A Random Number'])
df_melt

                       Home                  Away             Type  Number
0         Oakland Athletics        Houston Astros       Attendance   10436
1          San Diego Padres  Arizona Diamondbacks       Attendance   10350
2          Seattle Mariners  San Francisco Giants       Attendance    8174
3     Philadelphia Phillies        Atlanta Braves       Attendance    8529
4             Miami Marlins        Tampa Bay Rays       Attendance    7062
...                     ...                   ...              ...     ...
4735   Arizona Diamondbacks      Colorado Rockies  A Random Number      42
4736         Houston Astros     Oakland Athletics  A Random Number      42
4737     Kansas City Royals       Minnesota Twins  A Random Number      42
4738    Los Angeles Dodgers     Milwaukee Brewers  A Random Number      42
4739   Washington Nationals        Boston Red Sox  A Random Number      42

[4740 rows x 4 columns]

### Question 2: Un-melt the above.

In [75]:
df_melt.pivot_table(index=['Home', 'Away'], columns='Type', values='Number').reset_index()

Type,Home,Away,A Random Number,Attendance
0,Arizona Diamondbacks,Atlanta Braves,42.0,9008.000000
1,Arizona Diamondbacks,Chicago Cubs,42.0,21227.666667
2,Arizona Diamondbacks,Cincinnati Reds,42.0,14524.666667
3,Arizona Diamondbacks,Colorado Rockies,42.0,11676.700000
4,Arizona Diamondbacks,Los Angeles Angels,42.0,15029.666667
...,...,...,...,...
535,Washington Nationals,San Diego Padres,42.0,29885.333333
536,Washington Nationals,San Francisco Giants,42.0,21221.333333
537,Washington Nationals,St. Louis Cardinals,42.0,7909.666667
538,Washington Nationals,Tampa Bay Rays,42.0,16334.500000
539,Washington Nationals,Toronto Blue Jays,42.0,19198.000000

### Question 3: Group by two columns, take the mean and unstack the result.

In [84]:
df = pd.read_csv('attendance.csv', index_col=['Date']).sort_index()
df.groupby(['Home', 'Away']).mean().unstack(0)

                                Attendance                                   \
Home                  Arizona Diamondbacks Atlanta Braves Baltimore Orioles
Away
Arizona Diamondbacks                   NaN   19975.500000               NaN
Atlanta Braves                 9008.000000            NaN      13512.333333
Baltimore Orioles                      NaN            NaN               NaN
Boston Red Sox                         NaN   38242.500000       9289.200000
Chicago Cubs                  21227.666667   18482.250000               NaN
Chicago White Sox                      NaN            NaN      16689.333333
Cincinnati Reds               14524.666667   23934.000000               NaN
Cleveland Indians                      NaN            NaN      10467.000000
Colorado Rockies              11676.700000   21980.500000               NaN
Detroit Tigers                         NaN            NaN       8165.333333
Houston Astros                         NaN            NaN       8645.666667
Kansas City Royals                     NaN            NaN       6751.500000
Los Angeles Angels            15029.666667            NaN      11619.666667
Los Angeles Dodgers           23598.333333   40363.000000               NaN
Miami Marlins                  5887.000000   25624.600000       9230.500000
Milwaukee Brewers              9279.333333   37079.000000               NaN
Minnesota Twins                        NaN            NaN       7430.666667
New York Mets                 10236.333333   29323.444444       9507.500000
New York Yankees                       NaN   38301.000000      10155.200000
Oakland Athletics              7889.000000            NaN       7765.666667
Philadelphia Phillies          7643.000000   27303.000000               NaN
Pittsburgh Pirates             8106.333333   34729.250000               NaN
San Diego Padres              11290.666667   32621.000000               NaN
San Francisco Giants          12564.000000   34654.666667               NaN
Seattle Mariners              15318.666667            NaN       4603.500000
St. Louis Cardinals           13761.750000   36922.000000               NaN
Tampa Bay Rays                         NaN   38632.333333       9553.888889
Texas Rangers                  7556.000000            NaN       9600.750000
Toronto Blue Jays                      NaN   21504.000000      10526.375000
Washington Nationals          12329.333333   28622.800000      21203.333333

                                                                      \
Home                  Boston Red Sox  Chicago Cubs Chicago White Sox
Away
Arizona Diamondbacks             NaN  34617.000000               NaN
Atlanta Braves           9277.000000  10343.000000               NaN
Baltimore Orioles       21156.000000           NaN      16922.333333
Boston Red Sox                   NaN           NaN      36132.333333
Chicago Cubs                     NaN           NaN      38375.000000
Chicago White Sox        4695.000000  39676.000000               NaN
Cincinnati Reds                  NaN  26594.700000      24130.000000
Cleveland Indians       30595.333333  34213.500000      16335.200000
Colorado Rockies                 NaN  25256.500000               NaN
Detroit Tigers           4690.666667           NaN      21234.777778
Houston Astros          22663.000000           NaN      34322.666667
Kansas City Royals      25118.750000  31826.666667      13911.250000
Los Angeles Angels       9324.666667           NaN      25150.333333
Los Angeles Dodgers              NaN  10343.000000               NaN
Miami Marlins           19822.666667  35169.666667               NaN
Milwaukee Brewers                NaN  17023.333333               NaN
Minnesota Twins         30218.333333  24998.000000      16138.555556
New York Mets           31200.000000  10225.333333               NaN
New York Yankees        35349.900000           NaN      28001.666667
Oakland Athletics        9279.000000           NaN      21767.000000
Philadelphia Phillies   32809.666667  31711.750000               NaN
Pittsburgh Pirates               NaN  17363.700000      19226.000000
San Diego Padres                 NaN  23901.333333               NaN
San Francisco Giants             NaN  32061.000000               NaN
Seattle Mariners         4598.500000           NaN      30741.000000
St. Louis Cardinals              NaN  34934.625000      15266.666667
Tampa Bay Rays          19742.333333           NaN      19127.000000
Texas Rangers           30053.000000           NaN       8936.666667
Toronto Blue Jays       21050.111111           NaN      14700.666667
Washington Nationals             NaN  11143.500000               NaN

                                                                          \
Home                  Cincinnati Reds Cleveland Indians Colorado Rockies
Away
Arizona Diamondbacks      7886.333333               NaN     19891.777778
Atlanta Braves           27634.750000               NaN     28790.000000
Baltimore Orioles                 NaN      12788.000000              NaN
Boston Red Sox                    NaN      23328.333333              NaN
Chicago Cubs             22582.888889       8306.500000     34951.666667
Chicago White Sox        10228.000000      14071.428571              NaN
Cincinnati Reds                   NaN       9493.000000     17389.000000
Cleveland Indians        12548.666667               NaN              NaN
Colorado Rockies         20846.000000               NaN              NaN
Detroit Tigers           23158.333333      14487.875000              NaN
Houston Astros                    NaN      20120.500000      8632.000000
Kansas City Royals                NaN      15185.875000              NaN
Los Angeles Angels                NaN      18664.333333              NaN
Los Angeles Dodgers      28469.333333               NaN     28323.600000
Miami Marlins            20729.250000               NaN     34284.666667
Milwaukee Brewers        20916.333333      18033.000000     29573.750000
Minnesota Twins          17612.000000       9575.200000              NaN
New York Mets            18690.666667               NaN     14494.000000
New York Yankees                  NaN       8156.250000              NaN
Oakland Athletics                 NaN      14386.666667     25988.333333
Philadelphia Phillies    16557.333333               NaN     18161.000000
Pittsburgh Pirates       17150.300000               NaN     26759.000000
San Diego Padres         15012.000000               NaN     19860.625000
San Francisco Giants     10432.750000               NaN     26270.625000
Seattle Mariners                  NaN      20152.333333     27884.000000
St. Louis Cardinals      17976.500000      19703.500000     40676.750000
Tampa Bay Rays                    NaN      21114.000000              NaN
Texas Rangers                     NaN      11198.000000     18822.333333
Toronto Blue Jays                 NaN      10444.000000              NaN
Washington Nationals     16869.500000               NaN     20898.000000

                                      ...                        \
Home                  Detroit Tigers  ... Philadelphia Phillies
Away                                  ...
Arizona Diamondbacks             NaN  ...          22564.500000
Atlanta Braves                   NaN  ...          15886.200000
Baltimore Orioles       19240.000000  ...          19509.333333
Boston Red Sox          17167.000000  ...          15354.333333
Chicago Cubs             8000.000000  ...          17559.000000
Chicago White Sox       14382.111111  ...                   NaN
Cincinnati Reds                  NaN  ...          26572.666667
Cleveland Indians       13599.300000  ...                   NaN
Colorado Rockies                 NaN  ...          21885.000000
Detroit Tigers                   NaN  ...                   NaN
Houston Astros          13379.333333  ...                   NaN
Kansas City Royals      11819.100000  ...                   NaN
Los Angeles Angels      24281.000000  ...                   NaN
Los Angeles Dodgers              NaN  ...          28880.333333
Miami Marlins                    NaN  ...          17515.625000
Milwaukee Brewers       11877.000000  ...          10479.250000
Minnesota Twins         12298.250000  ...                   NaN
New York Mets                    NaN  ...          19057.333333
New York Yankees         8000.000000  ...          38481.000000
Oakland Athletics       12689.666667  ...                   NaN
Philadelphia Phillies            NaN  ...                   NaN
Pittsburgh Pirates       7387.500000  ...          23543.250000
San Diego Padres                 NaN  ...          24432.666667
San Francisco Giants             NaN  ...           9877.000000
Seattle Mariners         9177.666667  ...                   NaN
St. Louis Cardinals     13377.500000  ...          10869.333333
Tampa Bay Rays          16853.000000  ...          24477.000000
Texas Rangers           16050.500000  ...                   NaN
Toronto Blue Jays       17332.666667  ...                   NaN
Washington Nationals             NaN  ...          18302.375000

                                                           \
Home                  Pittsburgh Pirates San Diego Padres
Away
Arizona Diamondbacks         8477.000000     25360.600000
Atlanta Braves              10846.000000     37861.666667
Baltimore Orioles                    NaN              NaN
Boston Red Sox                       NaN              NaN
Chicago Cubs                 7763.333333     16244.666667
Chicago White Sox           10126.500000              NaN
Cincinnati Reds              9938.888889     37646.750000
Cleveland Indians           16792.333333              NaN
Colorado Rockies             7550.000000     31225.000000
Detroit Tigers               9284.000000              NaN
Houston Astros                       NaN     35792.666667
Kansas City Royals           4868.000000              NaN
Los Angeles Angels                   NaN     34471.000000
Los Angeles Dodgers          9800.000000     33461.333333
Miami Marlins                6606.750000     29551.333333
Milwaukee Brewers           13764.444444     15250.000000
Minnesota Twins                      NaN              NaN
New York Mets               21059.333333     16070.500000
New York Yankees                     NaN              NaN
Oakland Athletics                    NaN     37756.500000
Philadelphia Phillies       23512.333333     40952.666667
Pittsburgh Pirates                   NaN     15250.000000
San Diego Padres             4533.250000              NaN
San Francisco Giants         6507.750000     20275.222222
Seattle Mariners                     NaN     15250.000000
St. Louis Cardinals          9952.000000     15250.000000
Tampa Bay Rays                       NaN              NaN
Texas Rangers                        NaN              NaN
Toronto Blue Jays                    NaN              NaN
Washington Nationals        13171.666667     29733.000000

                                                             \
Home                  San Francisco Giants Seattle Mariners
Away
Arizona Diamondbacks          18499.444444     14471.000000
Atlanta Braves                30304.000000              NaN
Baltimore Orioles                      NaN      6340.666667
Boston Red Sox                         NaN     18655.333333
Chicago Cubs                  12285.500000              NaN
Chicago White Sox                      NaN      7281.666667
Cincinnati Reds                4581.333333              NaN
Cleveland Indians                      NaN     10123.000000
Colorado Rockies              16205.300000     12010.000000
Detroit Tigers                         NaN      7515.333333
Houston Astros                28333.000000     12498.555556
Kansas City Royals                     NaN     21113.500000
Los Angeles Angels            11845.000000     25613.222222
Los Angeles Dodgers           29237.777778      8998.500000
Miami Marlins                  6772.750000              NaN
Milwaukee Brewers             21565.750000              NaN
Minnesota Twins                        NaN      8317.333333
New York Mets                 24160.333333              NaN
New York Yankees                       NaN     17092.000000
Oakland Athletics             35338.666667     16323.900000
Philadelphia Phillies         17069.666667              NaN
Pittsburgh Pirates            29220.666667              NaN
San Diego Padres              22948.800000              NaN
San Francisco Giants                   NaN      8405.666667
Seattle Mariners                       NaN              NaN
St. Louis Cardinals           23498.666667              NaN
Tampa Bay Rays                         NaN     13672.500000
Texas Rangers                  7359.000000     14694.400000
Toronto Blue Jays                      NaN     25635.333333
Washington Nationals          26628.333333              NaN

                                                                        \
Home                  St. Louis Cardinals Tampa Bay Rays Texas Rangers
Away
Arizona Diamondbacks         27716.666667            NaN  26971.500000
Atlanta Braves               31421.000000            NaN           NaN
Baltimore Orioles                     NaN    7658.000000  25259.333333
Boston Red Sox                        NaN   11184.100000  29056.500000
Chicago Cubs                 35979.400000            NaN           NaN
Chicago White Sox                     NaN   17383.000000  28109.000000
Cincinnati Reds              21819.300000            NaN           NaN
Cleveland Indians            16254.500000    9868.500000  26152.666667
Colorado Rockies             13401.666667            NaN  16040.000000
Detroit Tigers               26244.500000   16881.500000  30631.333333
Houston Astros                        NaN    6812.333333  28156.800000
Kansas City Royals           32549.333333    5146.000000  30349.000000
Los Angeles Angels                    NaN   12457.333333  20364.800000
Los Angeles Dodgers          36203.500000            NaN           NaN
Miami Marlins                24566.333333   19983.000000           NaN
Milwaukee Brewers            24613.222222            NaN           NaN
Minnesota Twins              32147.666667   12296.666667  32785.000000
New York Mets                12937.333333    7338.000000           NaN
New York Yankees                      NaN    8659.000000  28458.000000
Oakland Athletics                     NaN    3254.000000  25554.000000
Philadelphia Phillies        12905.250000    7397.500000           NaN
Pittsburgh Pirates           27556.777778            NaN           NaN
San Diego Padres             35629.666667            NaN  30051.333333
San Francisco Giants         34552.333333            NaN  25370.500000
Seattle Mariners                      NaN    8542.333333  24290.444444
St. Louis Cardinals                   NaN            NaN           NaN
Tampa Bay Rays                        NaN            NaN  28104.666667
Texas Rangers                         NaN    3904.500000           NaN
Toronto Blue Jays                     NaN    8818.111111  24566.333333
Washington Nationals         12938.000000    7394.500000           NaN


Home                  Toronto Blue Jays Washington Nationals
Away
Arizona Diamondbacks                NaN          7876.250000
Atlanta Braves              1605.666667         14388.000000
Baltimore Orioles          15740.900000         14809.000000
Boston Red Sox              9547.500000         35990.666667
Chicago Cubs                        NaN         30282.000000
Chicago White Sox          14606.750000                  NaN
Cincinnati Reds                     NaN          8432.666667
Cleveland Indians          14405.500000                  NaN
Colorado Rockies                    NaN         25604.333333
Detroit Tigers             14800.333333                  NaN
Houston Astros              5413.666667                  NaN
Kansas City Royals         13942.000000                  NaN
Los Angeles Angels          1387.666667                  NaN
Los Angeles Dodgers                 NaN         32056.250000
Miami Marlins               5353.000000         14676.444444
Milwaukee Brewers                   NaN         13927.500000
Minnesota Twins            14707.000000                  NaN
New York Mets                       NaN         23357.750000
New York Yankees           12719.111111                  NaN
Oakland Athletics          14926.000000                  NaN
Philadelphia Phillies       1225.000000         14722.300000
Pittsburgh Pirates                  NaN         16175.333333
San Diego Padres                    NaN         29885.333333
San Francisco Giants                NaN         21221.333333
Seattle Mariners            6274.666667                  NaN
St. Louis Cardinals                 NaN          7909.666667
Tampa Bay Rays              7020.000000         16334.500000
Texas Rangers              11217.500000                  NaN
Toronto Blue Jays                   NaN         19198.000000
Washington Nationals        1372.500000                  NaN

[30 rows x 30 columns]

### Question 4: Group by two columns, take the mean, and unstack the result, and flatten the columns.

In [86]:
def flatten_cols(df):
    cols = ['_'.join(map(str, vals))
            for vals in df.columns.to_flat_index()]
    df.columns = cols
    return df

In [87]:
df.groupby(['Home', 'Away']).mean().unstack().pipe(flatten_cols)

,Attendance_Arizona Diamondbacks,Attendance_Atlanta Braves,Attendance_Baltimore Orioles,Attendance_Boston Red Sox,Attendance_Chicago Cubs,Attendance_Chicago White Sox,Attendance_Cincinnati Reds,Attendance_Cleveland Indians,Attendance_Colorado Rockies,Attendance_Detroit Tigers,...,Attendance_Philadelphia Phillies,Attendance_Pittsburgh Pirates,Attendance_San Diego Padres,Attendance_San Francisco Giants,Attendance_Seattle Mariners,Attendance_St. Louis Cardinals,Attendance_Tampa Bay Rays,Attendance_Texas Rangers,Attendance_Toronto Blue Jays,Attendance_Washington Nationals
Home,,,,,,,,,,,,,,,,,,,,,
Arizona Diamondbacks,NaN,9008.000000,NaN,NaN,21227.666667,NaN,14524.666667,NaN,11676.700000,NaN,...,7643.000000,8106.333333,11290.666667,12564.000000,15318.666667,13761.750000,NaN,7556.000000,NaN,12329.333333
Atlanta Braves,19975.500000,NaN,NaN,38242.500000,18482.250000,NaN,23934.000000,NaN,21980.500000,NaN,...,27303.000000,34729.250000,32621.000000,34654.666667,NaN,36922.000000,38632.333333,NaN,21504.000000,28622.800000
Baltimore Orioles,NaN,13512.333333,NaN,9289.200000,NaN,16689.333333,NaN,10467.000000,NaN,8165.333333,...,NaN,NaN,NaN,NaN,4603.500000,NaN,9553.888889,9600.750000,10526.375000,21203.333333
Boston Red Sox,NaN,9277.000000,21156.000000,NaN,NaN,4695.000000,NaN,30595.333333,NaN,4690.666667,...,32809.666667,NaN,NaN,NaN,4598.500000,NaN,19742.333333,30053.000000,21050.111111,NaN
Chicago Cubs,34617.000000,10343.000000,NaN,NaN,NaN,39676.000000,26594.700000,34213.500000,25256.500000,NaN,...,31711.750000,17363.700000,23901.333333,32061.000000,NaN,34934.625000,NaN,NaN,NaN,11143.500000
Chicago White Sox,NaN,NaN,16922.333333,36132.333333,38375.000000,NaN,24130.000000,16335.200000,NaN,21234.777778,...,NaN,19226.000000,NaN,NaN,30741.000000,15266.666667,19127.000000,8936.666667,14700.666667,NaN
Cincinnati Reds,7886.333333,27634.750000,NaN,NaN,22582.888889,10228.000000,NaN,12548.666667,20846.000000,23158.333333,...,16557.333333,17150.300000,15012.000000,10432.750000,NaN,17976.500000,NaN,NaN,NaN,16869.500000
Cleveland Indians,NaN,NaN,12788.000000,23328.333333,8306.500000,14071.428571,9493.000000,NaN,NaN,14487.875000,...,NaN,NaN,NaN,NaN,20152.333333,19703.500000,21114.000000,11198.000000,10444.000000,NaN
Colorado Rockies,19891.777778,28790.000000,NaN,NaN,34951.666667,NaN,17389.000000,NaN,NaN,NaN,...,18161.000000,26759.000000,19860.625000,26270.625000,27884.000000,40676.750000,NaN,18822.333333,NaN,20898.000000
Detroit Tigers,NaN,NaN,19240.000000,17167.000000,8000.000000,14382.111111,NaN,13599.300000,NaN,NaN,...,NaN,7387.500000,NaN,NaN,9177.666667,13377.500000,16853.000000,16050.500000,17332.666667,NaN
Houston Astros,23932.333333,NaN,27629.666667,24877.250000,NaN,31931.000000,NaN,23420.333333,25565.500000,15859.666667,...,NaN,NaN,30795.666667,NaN,20270.800000,NaN,30742.000000,28156.222222,25186.333333,NaN
Kansas City Royals,NaN,NaN,21587.000000,25054.666667,NaN,14823.200000,13552.333333,9724.600000,NaN,16473.444444,...,NaN,11468.500000,NaN,NaN,17287.000000,28240.333333,5041.000000,8971.000000,8118.666667,NaN
Los Angeles Angels,NaN,NaN,23558.666667,28963.666667,NaN,12602.250000,NaN,9798.666667,18410.333333,24561.000000,...,NaN,NaN,30776.000000,24487.000000,21682.900000,NaN,9200.500000,14353.888889,18884.333333,NaN
Los Angeles Dodgers,32984.800000,47278.333333,NaN,NaN,48324.250000,NaN,15185.666667,NaN,32665.222222,NaN,...,39998.666667,51086.333333,34935.400000,36434.700000,15578.000000,16547.666667,NaN,17742.666667,NaN,15035.333333
Miami Marlins,3840.000000,7963.666667,4284.000000,NaN,11071.666667,NaN,9515.000000,NaN,4797.000000,NaN,...,7076.700000,10018.000000,11553.250000,5959.000000,NaN,4943.666667,6452.000000,NaN,6227.500000,5795.300000
Milwaukee Brewers,16960.750000,14839.333333,NaN,NaN,24002.222222,37095.666667,24395.000000,NaN,29576.333333,17987.500000,...,24600.333333,18954.888889,13785.000000,35334.000000,NaN,24185.100000,NaN,NaN,NaN,32814.333333
Minnesota Twins,NaN,NaN,9691.000000,7241.000000,22004.000000,15943.888889,18358.500000,18027.750000,NaN,18963.300000,...,NaN,9551.666667,NaN,NaN,9761.333333,NaN,22208.666667,8176.500000,20557.250000,NaN
New York Mets,7816.666667,20238.500000,7982.500000,7984.000000,18639.500000,NaN,27235.666667,NaN,9065.666667,NaN,...,23009.625000,26231.333333,23893.666667,25980.666667,NaN,20627.666667,NaN,NaN,27023.333333,18685.875000
New York Yankees,NaN,9825.500000,24462.444444,31617.500000,NaN,14227.666667,NaN,34867.000000,NaN,9853.000000,...,35109.000000,NaN,NaN,NaN,36748.250000,NaN,21090.000000,23555.000000,19383.222222,10317.333333
Oakland Athletics,3892.500000,NaN,6036.000000,20557.000000,NaN,5927.000000,NaN,10769.000000,NaN,5347.500000,...,NaN,NaN,11316.500000,35569.333333,3948.000000,NaN,6558.666667,7219.777778,3104.500000,NaN
Philadelphia Phillies,22564.500000,15886.200000,19509.333333,15354.333333,17559.000000,NaN,26572.666667,NaN,21885.000000,NaN,...,NaN,23543.250000,24432.666667,9877.000000,NaN,10869.333333,24477.000000,NaN,NaN,18302.375000
Pittsburgh Pirates,8477.000000,10846.000000,NaN,NaN,7763.333333,10126.500000,9938.888889,16792.333333,7550.000000,9284.000000,...,23512.333333,NaN,4533.250000,6507.750000,NaN,9952.000000,NaN,NaN,NaN,13171.666667
San Diego Padres,25360.600000,37861.666667,NaN,NaN,16244.666667,NaN,37646.750000,NaN,31225.000000,NaN,...,40952.666667,15250.000000,NaN,20275.222222,15250.000000,15250.000000,NaN,NaN,NaN,29733.000000
San Francisco Giants,18499.444444,30304.000000,NaN,NaN,12285.500000,NaN,4581.333333,NaN,16205.300000,NaN,...,17069.666667,29220.666667,22948.800000,NaN,NaN,23498.666667,NaN,7359.000000,NaN,26628.333333
Seattle Mariners,14471.000000,NaN,6340.666667,18655.333333,NaN,7281.666667,NaN,10123.000000,12010.000000,7515.333333,...,NaN,NaN,NaN,8405.666667,NaN,NaN,13672.500000,14694.400000,25635.333333,NaN
St. Louis Cardinals,27716.666667,31421.000000,NaN,NaN,35979.400000,NaN,21819.300000,16254.500000,13401.666667,26244.500000,...,12905.250000,27556.777778,35629.666667,34552.333333,NaN,NaN,NaN,NaN,NaN,12938.000000
Tampa Bay Rays,NaN,NaN,7658.000000,11184.100000,NaN,17383.000000,NaN,9868.500000,NaN,16881.500000,...,7397.500000,NaN,NaN,NaN,8542.333333,NaN,NaN,3904.500000,8818.111111,7394.500000
Texas Rangers,26971.500000,NaN,25259.333333,29056.500000,NaN,28109.000000,NaN,26152.666667,16040.000000,30631.333333,...,NaN,NaN,30051.333333,25370.500000,24290.444444,NaN,28104.666667,NaN,24566.333333,NaN
Toronto Blue Jays,NaN,1605.666667,15740.900000,9547.500000,NaN,14606.750000,NaN,14405.500000,NaN,14800.333333,...,1225.000000,NaN,NaN,NaN,6274.666667,NaN,7020.000000,11217.500000,NaN,1372.500000
Washington Nationals,7876.250000,14388.000000,14809.000000,35990.666667,30282.000000,NaN,8432.666667,NaN,25604.333333,NaN,...,14722.300000,16175.333333,29885.333333,21221.333333,NaN,7909.666667,16334.500000,NaN,19198.000000,NaN